### PR TITLE
Removed jQuery

### PR DESCRIPTION
**Pull request by zetlen**
Removed jQuery and replaced its usage with direct DOM manipulation.

 - Removed script tag for jQuery itself
 - Wrote methods to replicate querying and CSS setting with native APIs
 - Slightly refactored style

### CODE REVIEW

**Review by charlesvestal — COMMENTED** [review]
i'm not totally clear on the applyProps array, do you find that more legible?

**Comment by zetlen** [comment]
Yeah, it's just a quick way to do backwards-compatible CSS setting. Basically a dead-simple version of what jQuery does. It's not very legible, no, but any more terse and it'd look magical.

**Comment by charlesvestal** [comment]
actual question: is terseness a goal? in sacrifice of legibility / understanding? I'm unsure on something this basic.

**Comment by zetlen** [comment]
Terseness by itself is totally bad, but it's good as a tool to counteract verbosity. Code is mostly for people to read, and I like to skip over the boring parts if I can. some chores are more annoying than others. For stuff that is uninteresting, like vendor prefixes, I slightly prefer terse over obvious.

jQuery is another way to do that, but it seemed a little heavy for this application. Instead I thought I'd do something boring in a few lines, instead of a bunch of repetitive things. But you can feel free to factor it out if it seems weird!

Also, if you don't want to support older browsers at all, you could remove it entirely.

**Pull request merged**
